# Generated by Django 5.1.3 on 2024-12-05 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subexams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('unitofmeasurement', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('subexam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subexams.subexam')),
            ],
        ),
    ]
