# Generated by Django 5.1.3 on 2024-12-05 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_alter_tests_method_alter_tests_unitofmeasurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tests',
            name='method',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tests',
            name='unitofmeasurement',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
