# Generated by Django 5.1.3 on 2024-11-14 03:42

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('midle_name', models.CharField(max_length=50)),
                ('first_surname', models.CharField(max_length=50)),
                ('second_surname', models.CharField(max_length=50)),
                ('birthdate', models.DateField(verbose_name='XYZ Date')),
                ('gender', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=128, verbose_name='address')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
