# Generated by Django 5.1.3 on 2024-12-05 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tests', '0003_alter_tests_method_alter_tests_unitofmeasurement'),
    ]

    operations = [
        migrations.CreateModel(
            name='referencevalue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1', models.CharField(blank=True, max_length=255, null=True)),
                ('value1', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('character1', models.CharField(blank=True, max_length=25, null=True)),
                ('value2', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('text2', models.CharField(blank=True, max_length=255, null=True)),
                ('value3', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('character2', models.CharField(blank=True, max_length=25, null=True)),
                ('value4', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('text3', models.CharField(blank=True, max_length=255, null=True)),
                ('value5', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('character5', models.CharField(blank=True, max_length=25, null=True)),
                ('value6', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('test', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tests.tests')),
            ],
        ),
    ]
